name: Deploy to Railway
on: [push]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install deps
        run: npm install
      - name: Build
        run: npm run build
      - name: Deploy
        uses: railwayapp-automation/railway-action@v1.2.9
        with:
          railwayToken: ${{ secrets.RAILWAY_TOKEN }}
